[font]
family = "monospace"
size = 11

[window]
padding = 4

[cursor]
shape = "block"
blinking = true

[colors]
background = '#141414'
foreground = '#d8d8d8'

[colors.extra]
zoom-indicator = '#323232'

[colors.normal]
black   = '#181818'
red     = '#ab4642'
green   = '#a1b56c'
yellow  = '#f7ca88'
blue    = '#7cafc2'
magenta = '#ba8baf'
cyan    = '#86c1b9'
white   = '#d8d8d8'

[colors.bright]
black   = '#282828'
red     = '#ab4642'
green   = '#a1b56c'
yellow  = '#f7ca88'
blue    = '#7cafc2'
magenta = '#ba8baf'
cyan    = '#86c1b9'
white   = '#f8f8f8'
